# Generated by Django 5.0.6 on 2024-07-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_rename_valor_unitario_venda_itemvenda_preco_unitario_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(auto_now_add=True),
        ),
    ]
