# Generated by Django 5.0.6 on 2024-07-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_alter_venda_data_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='tipo_pgto',
        ),
    ]
